#!/bin/bash

# Deploy AetherSwarm Contracts to Base (Sepolia or Mainnet)
# Usage: ./deploy-base.sh [sepolia|mainnet]

NETWORK=${1:-sepolia}

echo "🚀 Deploying AetherSwarm to Base $NETWORK"
echo "========================================="

if [ ! -f .env ]; then
    echo "❌ .env file missing"
    exit 1
fi
source .env

if [ -z "$DEPLOYER_PRIVATE_KEY" ]; then
    echo "❌ DEPLOYER_PRIVATE_KEY is not set in .env"
    exit 1
fi

if [ "$NETWORK" == "mainnet" ]; then
    RPC_URL="https://mainnet.base.org"
    VERIFIER_URL="https://api.basescan.org/api"
    CHAIN_ID=8453
    ENV_SUFFIX="_BASE_MAIN"
else
    RPC_URL="https://sepolia.base.org"
    VERIFIER_URL="https://api-sepolia.basescan.org/api"
    CHAIN_ID=84532
    ENV_SUFFIX="_BASE"
fi

echo "Target Network: $NETWORK (Chain ID: $CHAIN_ID)"
echo "RPC URL: $RPC_URL"

cd contracts

# Check balance
ADDRESS=$(cast wallet address --private-key $DEPLOYER_PRIVATE_KEY)
echo "Deployer: $ADDRESS"
BALANCE=$(cast balance $ADDRESS --rpc-url $RPC_URL)
echo "Balance: $BALANCE wei"

if [ "$BALANCE" == "0" ]; then
    echo "❌ No funds to deploy!"
    exit 1
fi

echo "🔨 Compiling..."
forge build

echo "📡 Deploying..."
forge script script/Deploy.s.sol:DeployContracts \
    --rpc-url $RPC_URL \
    --private-key $DEPLOYER_PRIVATE_KEY \
    --broadcast \
    --verify \
    --etherscan-api-key $BASESCAN_API_KEY \
    --verifier-url $VERIFIER_URL \
    -vvvv

if [ $? -eq 0 ]; then
    echo "✅ Deployment Successful!"
    
    # Read the output addresses from .contracts.env (generated by script)
    source .contracts.env
    
    echo ""
    echo "📝 Update your .env file with these values:"
    echo ""
    echo "CHAIN_ID=$CHAIN_ID"
    echo "DISCOVERY_REGISTRY_ADDRESS$ENV_SUFFIX=$AGENT_REGISTRY_ADDRESS"
    echo "REPUTATION_REGISTRY_ADDRESS$ENV_SUFFIX=$REPUTATION_REGISTRY_ADDRESS"
    echo "QUEST_LOGGER_ADDRESS$ENV_SUFFIX=$QUEST_LOGGER_ADDRESS"
    echo ""
else
    echo "❌ Deployment Failed"
    exit 1
fi
