[phases.setup]
nixPkgs = ["rustc", "cargo", "gcc", "cmake", "pkg-config"]

[phases.build]
cmds = [
    "cargo build --release",
    "mkdir -p ./bin",
    "cp ./target/release/verifier-agent ./bin/verifier-agent"
]

[start]
cmd = "./bin/verifier-agent"
